### ISSUE TITLE
[Error] Unable to use php build '5.4.38' for project 'project.dev', php fpm port isn't configured

### ISSUE THREAD

**Issue by ghost** [mdkholy/dashbrew#26]
My php builds from the enviroment.yaml file:

```
php::builds:
  5.6.0:
    installed: true
    default: true
    variants: dev
    extensions:
      xdebug:
        enabled: true
        version: stable
      xhprof:
        enabled: true
        version: latest
    fpm:
      port: 9002
      autostart: true
  5.4.38:
    installed: true
    variants: dev
    extensions:
      xdebug:
        enabled: true
        version: stable
    fpm: 9004
    autostart: true
  5.3.29:
    variants: dev
    extensions:
    fpm:
      port: 9003
      autostart: true
```

5.3.29 works fine wihtout any config needed. Am I doing something wrong?

**Comment by ghost** [comment]
I'm an idiot

```
 5.4.38:
    installed: true
    variants: dev
    extensions:
      xdebug:
        enabled: true
        version: stable
    fpm: 9004
    autostart: true
```

should be:

```
 5.4.38:
    installed: true
    variants: dev
    extensions:
      xdebug:
        enabled: true
        version: stable
    fpm:
        port: 9003
        autostart: true
    autostart: true
```
